language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO=2.0
  - DJANGO=1.9.9
  - DJANGO=1.8.18
  - DJANGO=1.10.8
  - DJANGO=1.11.7

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO=2.0

install:
  - pip install Django==$DJANGO times docutils pygments
  - python setup.py install
  - pip install codecov
  - pip install rq-scheduler

script: make test
services: redis

after_success:
  - codecov
